apiVersion: v1
kind: Service
metadata:
  name: docker-user
  labels:
    name: docker-user
spec:
  ports:
    - nodePort: 30164
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: docker-user
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-user
spec:
  selector:
    matchLabels:
      app: docker-user
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-user
    spec:
      containers:
        - name: docker-user
          image: maxx129/docker-user:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/otus_user?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

#            - name: POSTGRES_DB
#              value: otus_user
#            - name: POSTGRES_USER
#              value: cG9zdGdyZXM=
#            - name: POSTGRES_PASSWORD
#              value: cm9vdA==
#            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
#              value: update
#            - name: DB_HOST
#              value: db
#            - name: DB_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-configmap
#                  key: host
#            - name: DB_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-configmap
#                  key: name
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  key: postgres_user
#                  name: postgres-credentials
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_password
#
#            - name: POSTGRES_HOST
#              value: postgres-deployment
#            - name: DB_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-configmap
#                  key: name
#            - name: DB_USR
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_user
#            - name: DB_PSW
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_password

