server:
  port: 7001

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/otus_user #local
    saveDocContent: true
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    locations: "db/migration"
    enabled: false

ru:
  baccasoft:
    filter:
      excluded:
        - /swagger-ui.html
        - /v3/api-docs/**
        - /swagger-ui/**
